-- MySQL Script generated by MySQL Workbench
-- Sun Apr 27 00:13:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `railway` ;

-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `railway` DEFAULT CHARACTER SET utf8 ;
USE `railway` ;

-- -----------------------------------------------------
-- Table `railway`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`course` ;

CREATE TABLE IF NOT EXISTS `railway`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `imgPath` VARCHAR(512) NULL,
  `description` VARCHAR(1024) NULL,
  `createdTime` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway`.`chapter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`chapter` ;

CREATE TABLE IF NOT EXISTS `railway`.`chapter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `order_index` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chapter_course1_idx` (`course_id` ASC),
  CONSTRAINT `fk_chapter_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `railway`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `railway`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `railway`.`material` ;

CREATE TABLE IF NOT EXISTS `railway`.`material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chapter_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `order_index` INT NOT NULL,
  `category` VARCHAR(30) NOT NULL,
  `path` VARCHAR(512) NOT NULL,
  `createdTime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materials_chapter1_idx` (`chapter_id` ASC),
  CONSTRAINT `fk_materials_chapter1`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `railway`.`chapter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
